### ISSUE TITLE
Level 6.1 AdaptationSets should be set to Level 5.1

### ISSUE THREAD

**Issue by podborski** [nokiatech/omaf#10]
Adaptation Sets with extractor tracks (multi resolution tiles) have following codecs in their mimeTypes `codecs="resv.podv+ercm.hvc2.1.6.L183.80"` where `L183` refer to HEVC level 6.1. 

However the resolution of such Adaptation Sets (or Extractor tracks) is 3840x2304, which is still within 5.1 level limits. Therefore I assume it should be `L153` and not `L183` since OMAF viewport-dependent media profile is limited to level 5.1 and not 6.x

**Comment by nokiatech** [comment]
Thanks Dimitri for notifying this. We already have had a solution to this, but just not yet published to GitHub.

**Comment by nokiatech** [comment]
Fixed
