### ISSUE TITLE
OMAF Player for Android build failed due to couldn't find some files

### ISSUE THREAD

**Issue by you214** [nokiatech/omaf#12]
Hi, I tried OMAF player for Android app version.
But on my system Android Studio build fails in CMakelists.txt.
How can I fix it?
```
Gradle Daemon started in 1 s 905 ms
C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error: File C:\Users\xxx\omaf-build\omaf\Player\Lib\Android\Release/arm64-v8a/libOMAFPlayer.so does not exist.
C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error at C:\Users\xxxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt:20 (configure_file):
  configure_file Problem configuring file

C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error: File C:\Users\xxx\omaf-build\omaf\Player\Lib\Android\Release/arm64-v8a/libmp4vr_shared.so does not exist.
C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error at C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt:21 (configure_file):
  configure_file Problem configuring file

C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error: File C:\Users\xxx\omaf-build\omaf\Player\Lib\Android\Release/arm64-v8a/libheif_shared.so does not exist.
C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error at C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt:22 (configure_file):
  configure_file Problem configuring file

C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error: File C:\Users\xxx\omaf-build\omaf\Player\Lib\Android\Release/arm64-v8a/libdash.so does not exist.
C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt : C/C++ debug|arm64-v8a : CMake Error at C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt:23 (configure_file):
  configure_file Problem configuring file

C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt : C/C++ debug|arm64-v8a : Configuration failed.
executing external native build for cmake C:\Users\xxx\omaf-build\omaf\Player\VideoPlayback\Android\Handheld\app\CMakeLists.txt

CONFIGURE SUCCESSFUL in 25s
```

**Comment by elhigu** [comment]
Could you add complete reproduction steps so that we may reproduce and verify the problem? How did you try to compile everything?

**Comment by you214** [comment]
Thank you for your quick reply.  
I'm newer to Android build system, If I was doing wrong step, please point out.

My environment is Win10 & Android Studio 3.6.1.
1. Cloned this repository  with relevant depedencies to my local project
2. Opened project omaf > Player > Videoplayback > Android > Handheld > App
3. And Gradle sync started, but NDK not configured error has occurrd.
4. open File>Project Structure>SDK Location, specify location NDK 17.2.4988734 and Applied.
5. then gradle sync resumed, sync was seemed to be success.
6. I connected my android device to pc, and builded. then error above was indicated.

I think,,I have problem with cmake system on Android Studio.
I tried both version cmake 3.6 and 3.10, but both are failed.

and I also tried build-android-cmake-win.bat version, but  I got error "ANDROID_NDK is not set". 
Do you have any idea how can I fix it?

**Comment by elhigu** [comment]
I don't currently have environment on my home windows setup installed to try that out. I would say that trying to make the build-android-cmake-win.bat to work is the best chance to make it work. I'll check the env I have on my work desktop when I get back to office (might take some weeks though).

But this is how our CI setup is running the build test for that branch:

```
cd omaf
export OMAF_ROOT=$PWD
export ANDROID_NDK=C:\\NDKs\\r17c
cd $OMAF_ROOT/build
./build-android-cmake-win.bat abiv7
./build-android-cmake-win.bat abiv8
./build-android-cmake-win.bat abiv7 debug
./build-android-cmake-win.bat abiv8 debug
```

So it looks like at least you need to set your NDK path explicitly.

**Comment by you214** [comment]
Thank you for your quick and kindly support. 
I understand that it works with self created video.
thanks!
