### ISSUE TITLE
DEBUG build requires unbuilt RELEASE libraries

### ISSUE THREAD

**Issue by paulhiggs** [nokiatech/omaf#2]
when executing `build_visualstudio.bat vs2017 debug` the build on a newly cloned repository, the build process fails with the following error messages
`CMake Error at CMakeLists.txt:159 (file):`
`  file INSTALL cannot find`
`  "D:/code/nokia-omaf/Player/../Mp4/lib/Windows/Release/mp4vr_shared.dll".`

`CMake Error at CMakeLists.txt:160 (file):`
`  file INSTALL cannot find`
`  "D:/code/nokia-omaf/Player/../Mp4/lib/Windows/Release/mp4vr_shared.dll".`

**Comment by nokiatech** [comment]
Last two commits should solve this issue. Could you please check?

**Comment by paulhiggs** [comment]
It looks almost fixed, but there is an issue with the directories for the Release build of nokia/libdash.
Please see Issue https://github.com/nokiatech/omaf/issues/3

**Comment by paulhiggs** [comment]
Looks good now, Building debug works ok

**Comment by paulhiggs** [comment]
Looks good now, Building debug works ok
