### ISSUE TITLE
nokia\libdash error building for windows

### ISSUE THREAD

**Issue by paulhiggs** [nokiatech/omaf#3]
When trying to build nokia/libdash using `build-vs2017.bat` an incorrect directory is created - leading to the failure to build nokiatech/omaf.
`14: IF NOT EXIST ..\..\Lib\Windows\Release\VS2017 md ..\..\Lib\Windows\ReleaseVS2017`
should be 
`14: IF NOT EXIST ..\..\Lib\Windows\Release\VS2017 md ..\..\Lib\Windows\Release\VS2017`

**Comment by nokiatech** [comment]
Last two commits should solve this issue. Could you please check?

**Comment by paulhiggs** [comment]
does not look like the directory structure is resolved in libdash. `build-vs2017.bat` still has
`IF NOT EXIST ..\..\Lib\Windows\Debug\VS2017 md ..\..\Lib\Windows\Debug\VS2017`
`copy Debug\dash*.* ..\..\Lib\Windows\Debug\VS2017\`
`IF NOT EXIST ..\..\Lib\Windows\Release\VS2017 md ..\..\Lib\Windows\ReleaseVS2017`
`copy Release\dash*.* ..\..\Lib\Windows\Release\VS2017\`
`cd ..`

so directories look like this
![image](https://user-images.githubusercontent.com/3158807/42984640-97ba8434-8bbb-11e8-9bfe-14e2fbe01291.png)

**Comment by paulhiggs** [comment]
This is the latest output from `build-vs2017.bat` - note that `build-vs2015.bat` does not have the issue
`D:\code\nokia\libdash\build\build-vs2017>IF NOT EXIST ..\..\Lib\Windows\Release\VS2017 md ..\..\Lib\
Windows\ReleaseVS2017`

`D:\code\nokia\libdash\build\build-vs2017>copy Release\dash*.* ..\..\Lib\Windows\Release\VS2017\
Release\dash.dll`
`The system cannot find the path specified.`
`Release\dash.exp`
`The system cannot find the path specified.`
`Release\dash.lib`
`The system cannot find the path specified.`
 `       0 file(s) copied.`

**Comment by arihou** [comment]
Thanks for pointing this out. The LibDash Release directory issue for VS2017 should now be fixed with the latest LibDash commit. Please pull the latest LibDash code.

**Comment by paulhiggs** [comment]
Looks good!
