### ISSUE TITLE
Error build in windows

### ISSUE THREAD

**Issue by hengshaochen** [nokiatech/omaf#4]
Hi, 

I use Windows7 and follow the README step to build this application.

when executing visualstudio.bat vs2017 debug, the build process fails with the following error messages:

         c:\users\desktop\nokia-omaf\omaf\mp4\srcs\common\googlespheri
       calvideoheaderbox.cpp(21): error C2447: '{': missing function header (ol
       d-style formal list?) [C:\Users\Desktop\Nokia-OMAF\OMAF\Mp4\bui
       ld\vs2017-Release\common\common_for_lib.vcxproj]

    58 Warning(s)
    54 Error(s)

Time Elapsed 00:03:42.53

C:\Users\Desktop\Nokia-OMAF\OMAF\Mp4\build\vs2017-Release>cd ..
vs2017-Release\lib\Release\mp4vr_shared.*
The system cannot find the file specified.
        0 file(s) copied.
vs2017-Release\lib\Release\mp4vr_static*.*
The system cannot find the file specified.
        0 file(s) copied.
vs2017-Release\lib\Release\streamsegmenter_static*.*
The system cannot find the file specified.
        0 file(s) copied.

Hope someone can answer this. Thanks!

**Comment by hengshaochen** [comment]
By the way, the above error message is from building MP4. (I skipcreator and skipplayer)

**Comment by hengshaochen** [comment]
I put omaf-master folder and libdash-master folder in \NOKIA-OMAF\desktop\ and I use cmd and cd to Desktop\Nokia-OMAF\omaf-master\build. And run build-visualstudio.bat 

Is that anything wrong in above step? Thanks

**Comment by hengshaochen** [comment]
Also I used cmake-3.12.0-win64-x64

**Comment by paulhiggs** [comment]
Do you have the file `buildinfo.hpp` in `c:\users\desktop\nokia-omaf\omaf\mp4\build\`?

It seems like `MP4VR_BUILD_VERSION` is not defined, so the string concatenation is an error.

**Comment by hengshaochen** [comment]
Hi paulhiggs,

Thanks for answer my question. But no, I don't have buildinfo.hpp in c:\users\desktop\nokia-omaf\omaf\mp4\build\

Can you share your step how to build this project? I try many different way and still not able to do it.

**Comment by paulhiggs** [comment]
I also had this problem and reported it in Issue https://github.com/nokiatech/omaf/issues/2
This has now been fixed, so re-clone the repository and try again

**Comment by hengshaochen** [comment]
Finally, I built it. But comes the other issue in Monitor_Sample..

**Comment by hengshaochen** [comment]
Thanks paulhiggs. Looks good!
