### ISSUE TITLE
Is that necessary to build libdash before build this omaf project?

### ISSUE THREAD

**Issue by hengshaochen** [nokiatech/omaf#5]
Hi,

Is that necessary to build libdash before build this omaf project? or just need to place libdash and omaf in same directory? 

I have following error while building libdash:
C:\Users\Desktop\Nokia-OMAF\libdash-master\build\build-vs2017>IF NOT EX
IST ..\..\Lib\Windows\Release\VS2017 md ..\..\Lib\Windows\ReleaseVS2017

C:\Users\Desktop\Nokia-OMAF\libdash-master\build\build-vs2017>copy Rele
ase\dash*.* ..\..\Lib\Windows\Release\VS2017\
Release\dash.dll
The system cannot find the path specified.
Release\dash.exp
The system cannot find the path specified.
Release\dash.lib
The system cannot find the path specified.
        0 file(s) copied.

**Comment by arihou** [comment]
Hi hengshaochen.
Yes, you need build lbdash as well. there has been a fix on the VS2017 release build scripts for the LibDash code. Please pull it and retry building. That should fix the Release directory problem.

**Comment by hengshaochen** [comment]
Hi arihou,

Thanks for your reply. I download the latest version and repeat the install step. This time, the logs:

Time Elapsed 00:00:40.53

C:\Users\Desktop\Nokia-OMAF\libdash-master\build\build-vs2017>IF NOT EX
IST ..\..\Lib\Windows\Debug\VS2017 md ..\..\Lib\Windows\Debug\VS2017

C:\Users\Desktop\Nokia-OMAF\libdash-master\build\build-vs2017>copy Debu
g\dash*.* ..\..\Lib\Windows\Debug\VS2017\
Debug\dash.dll
Debug\dash.exp
Debug\dash.ilk
Debug\dash.lib
Debug\dash.pdb
        5 file(s) copied.

C:\Users\Desktop\Nokia-OMAF\libdash-master\build\build-vs2017>IF NOT EX
IST ..\..\Lib\Windows\Release\VS2017 md ..\..\Lib\Windows\Release\VS2017

C:\Users\Desktop\Nokia-OMAF\libdash-master\build\build-vs2017>copy Rele
ase\dash*.* ..\..\Lib\Windows\Release\VS2017\
Release\dash.dll
Release\dash.exp
Release\dash.lib
        3 file(s) copied.

Looks like the Release directory have 3 new files. But I still can not see the  bin folder and sampleplayer.exe

Thanks!
