### ISSUE TITLE
Latest visual studio not supported

### ISSUE THREAD

**Issue by paulhiggs** [nokiatech/omaf#6]
On my main system I keep visual studio updated, and while the Mp4 and Creator build OK, the player build fails
`Generating WINDOWS VS2017`
`From F:\nokia\omaf\Player`
`-----------------------------------------------------`
`-- Selecting Windows SDK version 10.0.16299.0 to target Windows 10.0.17134.`
`-- The C compiler identification is MSVC 19.13.26129.0`
`-- The CXX compiler identification is MSVC 19.13.26129.0`
`-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe`
`-- Check for working C compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works`
`-- Detecting C compiler ABI info`
`-- Detecting C compiler ABI info - done`
`-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual 
 Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe`
`-- Check for working CXX compiler: C:/Program Files (x86)/Microsoft Visual Studio/2017/Community/VC/Tools/MSVC/14.13.26128/bin/Hostx86/x64/cl.exe -- works`
`-- Detecting CXX compiler ABI info`
`-- Detecting CXX compiler ABI info - done`
`-- Detecting CXX compile features`
`-- Detecting CXX compile features - done`
`CMake Error at CMakeLists_MSVC.cmake:49 (message):`
`  Unsupported visual studio version!1913`
`Call Stack (most recent call first):`
`  CMakeLists.txt:97 (include)`

`-- Configuring incomplete, errors occurred!`
`See also "F:/nokia/omaf/Player/bld_windows_2017/CMakeFiles/CMakeOutput.log".`
`FAILED: 1'`

I will revert to my "less up to date" build system!

**Comment by paulhiggs** [comment]
Perhaps I did not have the latest version of Visual Studio 2017. Updating now to 5.7.5

**Comment by nokiatech** [comment]
Sorry for late reply.
There was no support for Visual Studio 2017 versions 15.5 and 15.6, but there was for older and newer versions. Should be now fixed.

**Comment by nokiatech** [comment]
Closing the issue as it should be now fixed and now further complains in 5 days
