### ISSUE TITLE
Sample-player throws a null pointer exception - Windows 7 not supported

### ISSUE THREAD

**Issue by paulhiggs** [nokiatech/omaf#7]
When starting the Monitor_Sample in visual studio, a null pointer exception is thrown at `gPlaybackControl = gOMAFPlay->getPlaybackControls();`.
It seems that `IOMAFPlayer::create  !Private::DeviceInfo::isCurrentDeviceSupported()` check fails, returning null and this is not expected in wWinMain().

Looks like only Windows 8 and 10 are supported
`NVRDeviceInfo.cpp`
`        bool_t isCurrentDeviceSupported()`
`        {`
`            return IsWindows8OrGreater();// || IsWindows10OrGreater();`
`        }'

**Comment by arihou** [comment]
Windows 7 is not supported. But if you'd like to experiment with it; as a simple work-round; you can simply modify the return line to "return true".

**Comment by paulhiggs** [comment]
Windows 10 runs ok
