### ISSUE TITLE
Build succeeded but not able to open Monitor_Sample.exe

### ISSUE THREAD

**Issue by hengshaochen** [nokiatech/omaf#8]
Hi,

Build succeeded including libDash, omaf-mp4, omaf-creator, omaf-player. Then I use Visual Studio 2017 to build Monitor_Sample. Again, without any error. But when I try to open Monitor_Sample.exe, then the error message pop up: https://ibb.co/jY203d

I am using Windows7, is that cause the problem? How to solve this? Thanks!

**Comment by paulhiggs** [comment]
See my title of Issue https://github.com/nokiatech/omaf/issues/7
Windows 7 is not supported in  the codebase, needs to be Windows 8 of greater!

**Comment by hengshaochen** [comment]
Hi paulhiggs,

I saw your issue before. But your error message is same as mine?

**Comment by paulhiggs** [comment]
I got a null pointer exception as I was running `Monitor_Sample.exe` in the Visual Studio debugger!. I will try to build and run in Windows 10 now.

**Comment by hengshaochen** [comment]
Thanks.

I got this error: https://ibb.co/dq8Xid

I think maybe is same issue....

**Comment by arihou** [comment]
If you read the readme, you can find that Windows 10 is the supported platform.
Further, the sample player does not have a file browser, but you need to hardcode the filename in the code. Did you do that? The sample player is just a simple sample, and does not have much error handling, so it may crash if you don't give the filename & location correctly.

**Comment by hengshaochen** [comment]
Thanks!
