### ISSUE TITLE
Error after after building: E/OMAF:VideoDecoderMediaFoundation: No decoders available for specified format! 

### ISSUE THREAD

**Issue by schwicko** [nokiatech/omaf#9]
Hello, 

I successfully build the Nokiatech-Omaf Implementation and already created the first DASH MPD with corresponding MPD and init files. Therefore, first I created the corresponding Kvazaar .265 files, packed by Mp4box, which were playble by the GPAC player and VLC without problems. Just to test, I created the a OMAF MP4 file, by: omafvi -i video_5000kbps_3840x2160_c265.mp4 -o omaf_test.mp4. This also worked without any error.
When I try to playback my omaf_test.mp4 or my DASH stream by the OMAFPlayer SDK example, excecuted by VisualStudio 2017, the player-window stays black and nothing happens. 
In the logfile I found the two inconsitences:
E/OMAF:VideoDecoderMediaFoundation: No decoders available for specified format!
E/OMAF:VideoDecoderManager: Video decoder reserve failed
I tried playback by excecuting via cmd and got the same error. I also tried playback with the provided testfile omaf_360.heic, but the player-window stays black.

I work on Win10 64bit, used the build-visualstudio.bat vs2017 version and installed cmake previously. I have installed ffmpeg and kvazaar, for other evaluations. The respective en/decoders are already installed, either by kvazaar or by the omaf build, or am I wrong?
My omaf-build root looks exactly as described, as I used git for cloning (all adjacent in directory omaf-build).
(git clone https://github.com/nokia/libdash
git clone --single-branch -b OMAF https://github.com/nokiatech/heif.git)
git clone https://github.com/nokiatech/omaf.git)

Any suggestions what I may have done wrong? Thanks in advance

**Comment by nokiatech** [comment]
Dear @schwicko 
Thanks for the detailed description. It seems that your Windows is missing HEVC video decoder. The decoder is not explicitly listed as a depencency in the OMAF project, but we have stated in the readme: " _OMAF Player requires in practice an HW accelerated HEVC decoder on Windows, available e.g. with NVidia 10xx display cards._" I assume your PC doesn't have such a graphics card? If so, then the option is to get HEVC video extension from Microsoft Store (0,99€), i.e. a SW HEVC decoder. Please note that it is able to playback 4K video only at 10 fps or less, depending on your CPU.

**Comment by schwicko** [comment]
Thanks for the fast response @nokiatech and for providing this build. I didn't see this simple note in the readme... but it solved my problem, as now my video is displayed by the player. Even though, with only 2 degrees of freedom, i.e. left and right. But I assume, up, down, zoom-in, zoom-out are just not provided, right?

**Comment by nokiatech** [comment]
Yes, the sample app only supports panning the view left and right.
